export interface TemplateConfig {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  pillar: 'futuristic' | 'cinematic' | 'bento' | 'artistic';
  pillarLabel: string;
  defaultBg: string;
  defaultText: string;
  defaultAccent: string;
  defaultMessage: string;
  effect: string;
}

// ═══════════════════════════════════════════════════════════════
// 20 PREMIUM VISUAL STYLE TEMPLATES
// Organized by 4 Aesthetic Pillars
// ═══════════════════════════════════════════════════════════════
export const TEMPLATES: Record<string, TemplateConfig> = {
  // ───────── FUTURISTIC / HIGH-TECH (5) ─────────
  nebula_glass: {
    id: 'nebula_glass',
    name: 'Nebula Glass',
    emoji: '🌌',
    gradient: 'linear-gradient(135deg, #7c3aed, #06b6d4)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#050510',
    defaultText: '#f0eeff',
    defaultAccent: '#7c3aed',
    defaultMessage: 'En este universo infinito, tú eres mi estrella favorita. Cada día a tu lado brilla más que el anterior.',
    effect: 'typewriter',
  },
  cyber_grid: {
    id: 'cyber_grid',
    name: 'Cyber Grid',
    emoji: '🕹️',
    gradient: 'linear-gradient(135deg, #00ff88, #00ccff)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#0a0a12',
    defaultText: '#e0ffe0',
    defaultAccent: '#00ff88',
    defaultMessage: 'Transmisión entrante... Este mensaje fue creado especialmente para ti con todo mi cariño.',
    effect: 'typewriter',
  },
  neural_pulse: {
    id: 'neural_pulse',
    name: 'Neural Pulse',
    emoji: '🧠',
    gradient: 'linear-gradient(135deg, #818cf8, #c084fc)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#060612',
    defaultText: '#e8e0ff',
    defaultAccent: '#818cf8',
    defaultMessage: 'Cada pensamiento me conecta contigo. Nuestra conexión es más fuerte que cualquier red neuronal.',
    effect: 'typewriter',
  },
  hologram_scan: {
    id: 'hologram_scan',
    name: 'Hologram Scan',
    emoji: '📡',
    gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#030308',
    defaultText: '#d0f0ff',
    defaultAccent: '#06b6d4',
    defaultMessage: 'Escaneando... Sujeto identificado como la persona más especial del universo.',
    effect: 'typewriter',
  },
  quantum_rift: {
    id: 'quantum_rift',
    name: 'Quantum Rift',
    emoji: '🌀',
    gradient: 'linear-gradient(135deg, #8b5cf6, #ec4899)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#020208',
    defaultText: '#f0e0ff',
    defaultAccent: '#8b5cf6',
    defaultMessage: 'A través de todas las dimensiones, en cada realidad posible, te elijo a ti.',
    effect: 'typewriter',
  },

  // ───────── CINEMATIC & MOODY (5) ─────────
  film_noir: {
    id: 'film_noir',
    name: 'Film Noir',
    emoji: '🎬',
    gradient: 'linear-gradient(135deg, #374151, #111827)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#0a0a0a',
    defaultText: '#f5f5f0',
    defaultAccent: '#9ca3af',
    defaultMessage: 'En esta película que es la vida, tú eres la escena que siempre quiero repetir.',
    effect: 'typewriter',
  },
  golden_age: {
    id: 'golden_age',
    name: 'Golden Age',
    emoji: '🏆',
    gradient: 'linear-gradient(135deg, #d4af37, #f3e5ab)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#1a1408',
    defaultText: '#fdfbf7',
    defaultAccent: '#d4af37',
    defaultMessage: 'Cada momento contigo es un recuerdo dorado que atesoro para siempre.',
    effect: 'typewriter',
  },
  cinematic_scroll: {
    id: 'cinematic_scroll',
    name: 'Cinematic Scroll',
    emoji: '🎞️',
    gradient: 'linear-gradient(135deg, #7c3aed, #2563eb)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#050505',
    defaultText: '#f5f5f0',
    defaultAccent: '#7c3aed',
    defaultMessage: 'Capítulo uno: El día que te conocí.\nCapítulo dos: Descubrí que eras especial.\nCapítulo tres: Supe que no quería perderte nunca.',
    effect: 'fadeUp',
  },
  velvet_dark: {
    id: 'velvet_dark',
    name: 'Velvet Dark',
    emoji: '🌹',
    gradient: 'linear-gradient(135deg, #be185d, #9f1239)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#0a0608',
    defaultText: '#fce7f3',
    defaultAccent: '#be185d',
    defaultMessage: 'En la oscuridad, tu luz es lo único que necesito para encontrar mi camino.',
    effect: 'typewriter',
  },
  fade_story: {
    id: 'fade_story',
    name: 'Fade Story',
    emoji: '📖',
    gradient: 'linear-gradient(135deg, #0f766e, #14b8a6)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#080808',
    defaultText: '#f0fdfa',
    defaultAccent: '#14b8a6',
    defaultMessage: 'Érase una vez...\nUna persona increíble que cambió mi mundo.\nEsa persona eres tú.',
    effect: 'fadeUp',
  },

  // ───────── MINIMALIST BENTO (5) ─────────
  bento_pastel: {
    id: 'bento_pastel',
    name: 'Bento Pastel',
    emoji: '🍱',
    gradient: 'linear-gradient(135deg, #f9a8d4, #a78bfa)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#faf8f5',
    defaultText: '#1a1a1a',
    defaultAccent: '#a78bfa',
    defaultMessage: 'Las cosas más bonitas de la vida son simples, como tenerte a mi lado.',
    effect: 'typewriter',
  },
  mono_grid: {
    id: 'mono_grid',
    name: 'Mono Grid',
    emoji: '▦',
    gradient: 'linear-gradient(135deg, #525252, #171717)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#111',
    defaultText: '#fff',
    defaultAccent: '#a3a3a3',
    defaultMessage: 'Sin adornos ni filtros. Solo quería decirte que eres increíble.',
    effect: 'typewriter',
  },
  zen_minimal: {
    id: 'zen_minimal',
    name: 'Zen Minimal',
    emoji: '🪷',
    gradient: 'linear-gradient(135deg, #6ee7b7, #a7f3d0)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#fefefe',
    defaultText: '#1a1a1a',
    defaultAccent: '#10b981',
    defaultMessage: 'En la calma encuentro tu nombre. En el silencio escucho tu risa.',
    effect: 'typewriter',
  },
  swiss_clean: {
    id: 'swiss_clean',
    name: 'Swiss Clean',
    emoji: '🇨🇭',
    gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#fff',
    defaultText: '#111',
    defaultAccent: '#e53935',
    defaultMessage: 'Diseñado con precisión. Como el cariño que siento por ti: exacto y sin dudas.',
    effect: 'typewriter',
  },
  soft_stack: {
    id: 'soft_stack',
    name: 'Soft Stack',
    emoji: '📚',
    gradient: 'linear-gradient(135deg, #f472b6, #fb923c)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#f0eee8',
    defaultText: '#1a1a1a',
    defaultAccent: '#e11d48',
    defaultMessage: 'Capa por capa, momento a momento, construimos algo hermoso juntos.',
    effect: 'typewriter',
  },

  // ───────── ARTISTIC / VIBRANT (5) ─────────
  liquid_dream: {
    id: 'liquid_dream',
    name: 'Liquid Dream',
    emoji: '🫧',
    gradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#0a0a1a',
    defaultText: '#fff',
    defaultAccent: '#a855f7',
    defaultMessage: 'Como un sueño líquido, fluyes por mis pensamientos sin poder detenerte.',
    effect: 'typewriter',
  },
  particle_burst: {
    id: 'particle_burst',
    name: 'Particle Burst',
    emoji: '✨',
    gradient: 'linear-gradient(135deg, #f59e0b, #ef4444)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#080810',
    defaultText: '#fff',
    defaultAccent: '#f59e0b',
    defaultMessage: '¡Cada chispa es un recuerdo nuestro! Mueve el mouse para crear más magia.',
    effect: 'typewriter',
  },
  brutalist_bold: {
    id: 'brutalist_bold',
    name: 'Brutalist Bold',
    emoji: '🔲',
    gradient: 'linear-gradient(135deg, #111, #333)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#f5f5f0',
    defaultText: '#111',
    defaultAccent: '#e53935',
    defaultMessage: 'SIN FILTROS. SIN EXCUSAS. SOLO LA VERDAD: ERES LO MEJOR QUE ME HA PASADO.',
    effect: 'typewriter',
  },
  neon_wave: {
    id: 'neon_wave',
    name: 'Neon Wave',
    emoji: '🌆',
    gradient: 'linear-gradient(135deg, #ff0066, #ff9900)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#0a001a',
    defaultText: '#fff',
    defaultAccent: '#ff0066',
    defaultMessage: 'En las luces de neón escribo tu nombre. En cada atardecer digital, pienso en ti.',
    effect: 'typewriter',
  },
  aurora_flow: {
    id: 'aurora_flow',
    name: 'Aurora Flow',
    emoji: '🌈',
    gradient: 'linear-gradient(135deg, #00ff88, #00ccff)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#020810',
    defaultText: '#fff',
    defaultAccent: '#00ff88',
    defaultMessage: 'Como una aurora boreal, tu presencia ilumina hasta las noches más oscuras.',
    effect: 'typewriter',
  },
};

// ═══ PILLAR METADATA ═══
export const PILLARS = [
  { id: 'futuristic', label: 'Futurista / High-Tech', emoji: '🚀', description: 'Glassmorphism, neón, y animaciones de otra dimensión' },
  { id: 'cinematic', label: 'Cinemático & Moody', emoji: '🎬', description: 'Tipografía elegante, texturas de película y profundidad' },
  { id: 'bento', label: 'Minimalista Bento', emoji: '🍱', description: 'Grids modulares, paletas limpias y micro-interacciones' },
  { id: 'artistic', label: 'Artístico / Vibrante', emoji: '🎨', description: 'Gradientes líquidos, partículas y tipografía audaz' },
] as const;
