export interface TemplateConfig {
  id: string;
  name: string;
  emoji: string;
  gradient: string;
  pillar: 'futuristic' | 'cinematic' | 'bento' | 'artistic';
  pillarLabel: string;
  defaultBg: string;
  defaultText: string;
  defaultAccent: string;
  defaultMessage: string;
  effect: string;
  tier: 'free' | 'basic' | 'premium' | 'vip';
  features: string[];
  advancedEffects?: boolean;
}

// ═══════════════════════════════════════════════════════════════
// 20 PREMIUM VISUAL STYLE TEMPLATES
// Tier System: Free (1) → Basic (5) → Premium (8) → VIP (6)
// ═══════════════════════════════════════════════════════════════
export const TEMPLATES: Record<string, TemplateConfig> = {
  // ───────── FREE TIER (1 template - Lead magnet) ─────────
  bento_pastel: {
    id: 'bento_pastel',
    name: 'Bento Pastel',
    emoji: '🍱',
    gradient: 'linear-gradient(135deg, #f9a8d4, #a78bfa)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#faf8f5',
    defaultText: '#1a1a1a',
    defaultAccent: '#a78bfa',
    defaultMessage: 'Las cosas más bonitas de la vida son simples, como tenerte a mi lado.',
    effect: 'typewriter',
    tier: 'free',
    features: ['Texto personalizable', 'Colores básicos', 'Link compartible', 'Marca de agua LinkSurprise'],
    advancedEffects: false,
  },

  // ───────── BASIC TIER ($3 - 5 templates) ─────────
  zen_minimal: {
    id: 'zen_minimal',
    name: 'Zen Minimal',
    emoji: '🪷',
    gradient: 'linear-gradient(135deg, #6ee7b7, #a7f3d0)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#fefefe',
    defaultText: '#1a1a1a',
    defaultAccent: '#10b981',
    defaultMessage: 'En la calma encuentro tu nombre. En el silencio escucho tu risa.',
    effect: 'typewriter',
    tier: 'basic',
    features: ['Sin marca de agua', 'Personalización completa', 'Música básica', '1 foto opcional'],
    advancedEffects: false,
  },
  swiss_clean: {
    id: 'swiss_clean',
    name: 'Swiss Clean',
    emoji: '🇨🇭',
    gradient: 'linear-gradient(135deg, #ef4444, #dc2626)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#fff',
    defaultText: '#111',
    defaultAccent: '#e53935',
    defaultMessage: 'Diseñado con precisión. Como el cariño que siento por ti: exacto y sin dudas.',
    effect: 'typewriter',
    tier: 'basic',
    features: ['Tipografía premium', 'Animación fade simple', 'Colores personalizables', 'Exportar HTML'],
    advancedEffects: false,
  },
  mono_grid: {
    id: 'mono_grid',
    name: 'Mono Grid',
    emoji: '▦',
    gradient: 'linear-gradient(135deg, #525252, #171717)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#111',
    defaultText: '#fff',
    defaultAccent: '#a3a3a3',
    defaultMessage: 'Sin adornos ni filtros. Solo quería decirte que eres increíble.',
    effect: 'typewriter',
    tier: 'basic',
    features: ['Modo oscuro', 'Grid minimalista', 'Animación typewriter', 'Link premium'],
    advancedEffects: false,
  },
  soft_stack: {
    id: 'soft_stack',
    name: 'Soft Stack',
    emoji: '📚',
    gradient: 'linear-gradient(135deg, #f472b6, #fb923c)',
    pillar: 'bento',
    pillarLabel: 'Minimalista',
    defaultBg: '#f0eee8',
    defaultText: '#1a1a1a',
    defaultAccent: '#e11d48',
    defaultMessage: 'Capa por capa, momento a momento, construimos algo hermoso juntos.',
    effect: 'typewriter',
    tier: 'basic',
    features: ['Animaciones suaves', 'Paleta pastel', 'Responsive perfecto', 'Soporte email'],
    advancedEffects: false,
  },
  fade_story: {
    id: 'fade_story',
    name: 'Fade Story',
    emoji: '📖',
    gradient: 'linear-gradient(135deg, #0f766e, #14b8a6)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#080808',
    defaultText: '#f0fdfa',
    defaultAccent: '#14b8a6',
    defaultMessage: 'Érase una vez...\nUna persona increíble que cambió mi mundo.\nEsa persona eres tú.',
    effect: 'fadeUp',
    tier: 'basic',
    features: ['Storytelling visual', 'Transiciones fade', 'Música ambiental', '2 fotos'],
    advancedEffects: false,
  },

  // ───────── PREMIUM TIER ($5-7 - 8 templates) ─────────
  cyber_grid: {
    id: 'cyber_grid',
    name: 'Cyber Grid',
    emoji: '🕹️',
    gradient: 'linear-gradient(135deg, #00ff88, #00ccff)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#0a0a12',
    defaultText: '#e0ffe0',
    defaultAccent: '#00ff88',
    defaultMessage: 'Transmisión entrante... Este mensaje fue creado especialmente para ti con todo mi cariño.',
    effect: 'typewriter',
    tier: 'premium',
    features: ['Grid animado 3D', 'Efecto scanline', 'Sonido interactivo', '5 fotos + música', 'Confeti digital'],
    advancedEffects: true,
  },
  neural_pulse: {
    id: 'neural_pulse',
    name: 'Neural Pulse',
    emoji: '🧠',
    gradient: 'linear-gradient(135deg, #818cf8, #c084fc)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#060612',
    defaultText: '#e8e0ff',
    defaultAccent: '#818cf8',
    defaultMessage: 'Cada pensamiento me conecta contigo. Nuestra conexión es más fuerte que cualquier red neuronal.',
    effect: 'typewriter',
    tier: 'premium',
    features: ['Partículas interactivas', 'Pulsos de luz', 'Hover effects avanzados', 'Password protection'],
    advancedEffects: true,
  },
  hologram_scan: {
    id: 'hologram_scan',
    name: 'Hologram Scan',
    emoji: '📡',
    gradient: 'linear-gradient(135deg, #06b6d4, #3b82f6)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#030308',
    defaultText: '#d0f0ff',
    defaultAccent: '#06b6d4',
    defaultMessage: 'Escaneando... Sujeto identificado como la persona más especial del universo.',
    effect: 'typewriter',
    tier: 'premium',
    features: ['Efecto holograma', 'Scan animation', 'Sonido futurista', 'Analytics básico'],
    advancedEffects: true,
  },
  golden_age: {
    id: 'golden_age',
    name: 'Golden Age',
    emoji: '🏆',
    gradient: 'linear-gradient(135deg, #d4af37, #f3e5ab)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#1a1408',
    defaultText: '#fdfbf7',
    defaultAccent: '#d4af37',
    defaultMessage: 'Cada momento contigo es un recuerdo dorado que atesoro para siempre.',
    effect: 'typewriter',
    tier: 'premium',
    features: ['Textura film grain', 'Brillo dorado', 'Transiciones cine', '8 fotos + playlist'],
    advancedEffects: true,
  },
  cinematic_scroll: {
    id: 'cinematic_scroll',
    name: 'Cinematic Scroll',
    emoji: '🎞️',
    gradient: 'linear-gradient(135deg, #7c3aed, #2563eb)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#050505',
    defaultText: '#f5f5f0',
    defaultAccent: '#7c3aed',
    defaultMessage: 'Capítulo uno: El día que te conocí.\nCapítulo dos: Descubrí que eras especial.\nCapítulo tres: Supe que no quería perderte nunca.',
    effect: 'fadeUp',
    tier: 'premium',
    features: ['Scroll cinematográfico', 'Parallax suave', 'Narrativa visual', 'Subtítulos estilo cine'],
    advancedEffects: true,
  },
  velvet_dark: {
    id: 'velvet_dark',
    name: 'Velvet Dark',
    emoji: '🌹',
    gradient: 'linear-gradient(135deg, #be185d, #9f1239)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#0a0608',
    defaultText: '#fce7f3',
    defaultAccent: '#be185d',
    defaultMessage: 'En la oscuridad, tu luz es lo único que necesito para encontrar mi camino.',
    effect: 'typewriter',
    tier: 'premium',
    features: ['Atmósfera dark romance', 'Partículas flotantes', 'Glow effect', '10 fotos'],
    advancedEffects: true,
  },
  liquid_dream: {
    id: 'liquid_dream',
    name: 'Liquid Dream',
    emoji: '🫧',
    gradient: 'linear-gradient(135deg, #a855f7, #ec4899)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#0a0a1a',
    defaultText: '#fff',
    defaultAccent: '#a855f7',
    defaultMessage: 'Como un sueño líquido, fluyes por mis pensamientos sin poder detenerte.',
    effect: 'typewriter',
    tier: 'premium',
    features: ['Gradiente líquido animado', 'Blob morphing', 'Micro-interacciones', 'Custom cursor'],
    advancedEffects: true,
  },
  neon_wave: {
    id: 'neon_wave',
    name: 'Neon Wave',
    emoji: '🌆',
    gradient: 'linear-gradient(135deg, #ff0066, #ff9900)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#0a001a',
    defaultText: '#fff',
    defaultAccent: '#ff0066',
    defaultMessage: 'En las luces de neón escribo tu nombre. En cada atardecer digital, pienso en ti.',
    effect: 'typewriter',
    tier: 'premium',
    features: ['Neón glow animado', 'Ondas de color', 'Synthwave vibes', 'Playlist integrada'],
    advancedEffects: true,
  },

  // ───────── VIP TIER ($9-12 - 6 templates ULTRA PREMIUM) ─────────
  nebula_glass: {
    id: 'nebula_glass',
    name: 'Nebula Glass',
    emoji: '🌌',
    gradient: 'linear-gradient(135deg, #7c3aed, #06b6d4)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#050510',
    defaultText: '#f0eeff',
    defaultAccent: '#7c3aed',
    defaultMessage: 'En este universo infinito, tú eres mi estrella favorita. Cada día a tu lado brilla más que el anterior.',
    effect: 'typewriter',
    tier: 'vip',
    features: ['Glassmorphism 3D avanzado', 'Nebulosa animada con WebGL', 'Partículas estelares interactivas', 'Profundidad parallax multi-capa', 'Música espacial inmersiva', '15 fotos + video background', 'Dominio personalizado gratis', 'Certificado de amor NFT'],
    advancedEffects: true,
  },
  quantum_rift: {
    id: 'quantum_rift',
    name: 'Quantum Rift',
    emoji: '🌀',
    gradient: 'linear-gradient(135deg, #8b5cf6, #ec4899)',
    pillar: 'futuristic',
    pillarLabel: 'Futurista',
    defaultBg: '#020208',
    defaultText: '#f0e0ff',
    defaultAccent: '#8b5cf6',
    defaultMessage: 'A través de todas las dimensiones, en cada realidad posible, te elijo a ti.',
    effect: 'typewriter',
    tier: 'vip',
    features: ['Portal cuántico animado', 'Distorsión espacio-temporal', 'Efecto glitch artístico', 'Viaje dimensional interactivo', 'Sonido binaural 8D', '20 fotos + GIFs animados', 'Analíticas avanzadas', 'Autodestrucción programable'],
    advancedEffects: true,
  },
  film_noir: {
    id: 'film_noir',
    name: 'Film Noir',
    emoji: '🎬',
    gradient: 'linear-gradient(135deg, #374151, #111827)',
    pillar: 'cinematic',
    pillarLabel: 'Cinemático',
    defaultBg: '#0a0a0a',
    defaultText: '#f5f5f0',
    defaultAccent: '#9ca3af',
    defaultMessage: 'En esta película que es la vida, tú eres la escena que siempre quiero repetir.',
    effect: 'typewriter',
    tier: 'vip',
    features: ['Blanco y negro cinematográfico', 'Grano de película real', 'Iluminación dramática dinámica', 'Transiciones tipo cine clásico', 'Banda sonora jazz/noir', 'Story board profesional', 'Créditos finales personalizados', 'Trailer descargable'],
    advancedEffects: true,
  },
  ethereal_dream: {
    id: 'ethereal_dream',
    name: 'Ethereal Dream',
    emoji: '☁️',
    gradient: 'linear-gradient(135deg, #c4b5fd, #ddd6fe)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#f5f3ff',
    defaultText: '#4c1d95',
    defaultAccent: '#a78bfa',
    defaultMessage: 'Flotando en un sueño etéreo, donde solo existimos tú y yo en perfecta armonía.',
    effect: 'fadeUp',
    tier: 'vip',
    features: ['Nubes volumétricas animadas', 'Rayos de luz god rays', 'Flotación suave anti-gravedad', 'Partículas de polvo mágico', 'Ambiente sonoro etéreo', 'Galería flotante 3D', 'Mensaje en botella virtual', 'Experiencia ASMR visual'],
    advancedEffects: true,
  },
  watercolor_bliss: {
    id: 'watercolor_bliss',
    name: 'Watercolor Bliss',
    emoji: '🎨',
    gradient: 'linear-gradient(135deg, #f472b6, #fb923c, #fbbf24)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#fffbeb',
    defaultText: '#78350f',
    defaultAccent: '#f59e0b',
    defaultMessage: 'Cada pincelada de amor crea un masterpiece único, irrepetible, como nosotros.',
    effect: 'typewriter',
    tier: 'vip',
    features: ['Acuarela fluida simulada', 'Mezcla de colores en tiempo real', 'Pinceladas animadas a mano', 'Textura papel artístico', 'Galería tipo museo', 'Firma digital personalizada', 'Time-lapse de creación', 'Print HD descargable'],
    advancedEffects: true,
  },
  aurora_flow: {
    id: 'aurora_flow',
    name: 'Aurora Flow',
    emoji: '🌈',
    gradient: 'linear-gradient(135deg, #00ff88, #00ccff, #7c3aed)',
    pillar: 'artistic',
    pillarLabel: 'Artístico',
    defaultBg: '#020810',
    defaultText: '#fff',
    defaultAccent: '#00ff88',
    defaultMessage: 'Como una aurora boreal, tu presencia ilumina hasta las noches más oscuras.',
    effect: 'typewriter',
    tier: 'vip',
    features: ['Aurora boreal procedural', 'Dance of lights interactivo', 'Reacción al movimiento mouse', 'Espectro completo RGB dinámico', 'Soundtrack nórdico ambiental', 'Mapa estelar personalizado', 'Mensaje codificado en luces', 'Experiencia 360°'],
    advancedEffects: true,
  },
};

// ═══ PILLAR METADATA ═══
export const PILLARS = [
  { id: 'futuristic', label: 'Futurista / High-Tech', emoji: '🚀', description: 'Glassmorphism, neón, y animaciones de otra dimensión' },
  { id: 'cinematic', label: 'Cinemático & Moody', emoji: '🎬', description: 'Tipografía elegante, texturas de película y profundidad' },
  { id: 'bento', label: 'Minimalista Bento', emoji: '🍱', description: 'Grids modulares, paletas limpias y micro-interacciones' },
  { id: 'artistic', label: 'Artístico / Vibrante', emoji: '🎨', description: 'Gradientes líquidos, partículas y tipografía audaz' },
] as const;

// Helper functions for tier system
export const getTierInfo = (tier: string) => {
  const tiers = {
    free: { name: 'Gratis', price: 0, color: '#10b981', icon: '🎁' },
    basic: { name: 'Básico', price: 3, color: '#3b82f6', icon: '⭐' },
    premium: { name: 'Premium', price: 5, color: '#8b5cf6', icon: '💎' },
    vip: { name: 'VIP Ultra', price: 9, color: '#f59e0b', icon: '👑' },
  };
  return tiers[tier as keyof typeof tiers] || tiers.basic;
};

export const getTemplatesByTier = (tier: string) => {
  return Object.values(TEMPLATES).filter(t => t.tier === tier);
};

export const TIER_ORDER = ['free', 'basic', 'premium', 'vip'];
